spring:
  main:
    banner-mode: off
  application:
    name: onwelo-recruitment-task
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/onwelo}
    username: ${POSTGRES_USERNAME:onwelo}
    password: ${POSTGRES_PASSWORD:onwelo}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect